version: "3"
services:
    jenkins:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: anvy-jenkins
      restart: always
      hostname: 'http://jenkins.anvy.com.br'
      ports:
        - '8081:8080'
        - '50000:50000'
      volumes:
        - /home/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
